name: pomoe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  fluent_ui: ^4.6.2
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  fluentui_system_icons: ^1.1.200
  flutter_riverpod: ^2.3.6
  system_theme: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
